### ISSUE TITLE
PageBuilder: Access main wrapper element

### ISSUE THREAD

**Issue by pimdewit** [blinkk/amagaki#173]
Hi, this is a small feature request.

Using the `PageBuilder` it would be really nice to modify the "main content" wrapper.
At the moment it seems to wrap all content in a `<main>` tag, it would be great to have more control over how this wrapper gets rendered.

For my use-case in particular I'd like to add an id (for skip-to-main-content) and classes.
Right now I hacked it together by using a partial with my own wrapper-element that basically renders other partials, which is breaking the nice css/js partial modules PageBuilder provides

What do you think?

**Comment by jeremydw** [comment]
Happy to make this customizable. Would you mind sharing the markup you've used to add the "skip to main content" feature? We would want to design a hook or method for you to override the default `<main>` behavior in the page builder config.

**Comment by pimdewit** [comment]
My current approach looks something like this (I'm using the Nunjucks renderer):

`index.yaml`:

```yaml
partials:
  - partial: main
    sub_partials:
      - partial: hero
        title: Hello, World!
```

`main.njk`:

```njk
<div id="main-content" class="page">
  {% for sub_partial in partial.sub_partials %}
    {% set partial = sub_partial %}
    {% include 'src/templates/partials/' ~ sub_partial.partial ~ "/" ~ sub_partial.partial ~ ".njk" %}
  {% endfor %}
</div>
```

The "skip to main content" link itself I put into the `PageBuilder.body.prepend` include (out of scope for this issue I think).
Thanks for considering it!

**Comment by jeremydw** [comment]
We could support adding a new option to `PageBuilderOptions` such as:

```
...
main: {
  attributes: {
    class: 'page',
    id: 'main-content,
  }
}
```

This would effectively render out the `<main>` element like:

```
<main id="main-content" class="page">
```

Would that work?

By the way; another way for you to achieve this without any changes to the plugin would be to use JavaScript to mutate the on-page `<main>` element (although that is not ideal, and I agree we should support this request).

We can use the same pattern for the `<header>`, `<body>`, and `<footer>` elements to permit customization.

**Comment by pimdewit** [comment]
Works for me 👍
Having the same api for `<header>`, `<body>` and `<footer>` would be a nice addition I think, this was one of the things I was looking for when first using the plugin.

> By the way; another way for you to achieve this without any changes to the plugin would be to use JavaScript to mutate the on-page \<main> element (although that is not ideal, and I agree we should support this request).

Yeah I'd love for everything to be as static as possible 😄 preferably no runtime dom changes.

Would you like me to open a PR for this?

**Comment by baptistebriel** [comment]
Hello!

I am having a similar issue. Would it be possible to add some specific classNames to the `<body>` element through the `PageBuilderOptions` as described above?

Thanks!

**Comment by jeremydw** [comment]
Hi All - I'm sorry for the late reply. The plugin already supports adding classes to the `body` element; see the definition here: https://github.com/blinkk/amagaki/blob/main/packages/amagaki-plugin-page-builder/src/page-builder.ts#L213

You can see an example of the options configuration here: https://github.com/blinkk/amagaki/blob/main/packages/amagaki-plugin-page-builder/example/amagaki.ts#L40 (but, add `class: 'myClassName'` to define the `body` class name).

I'll open a PR and add support for the same for `main` now.

**Comment by jeremydw** [comment]
The ability to customize `<main>` should be available in `@amagaki/amagaki-plugin-page-builder: 3.12.0` via https://github.com/blinkk/amagaki/pull/228
